[param]
interface_type = "Uart"
comport_uart = "COM3"
speed_uart = "2000000"
speed_jlink = "1000"
bl60x_brd = "IoTKitA"
bl60x_xtal = "40M"
aes_key = ""
aes_iv = ""
addr = "0x0"

[check_box]
partition_download = true
boot2_download = true
bin_download = true
media_download = false
use_romfs = false
mfg_download = false
ro_params_download = true
ckb_erase_all = "True"
encrypt = false
download_single = false

[input_path]
pt_bin_input = "C:\\msys64\\home\\msys\\bl602_rgb_controller\\tools\\flash_tool\\bl602\\partition\\partition_cfg_2M.toml"
boot2_bin_input = "C:\\msys64\\home\\msys\\bl602_rgb_controller\\tools\\flash_tool\\bl602\\builtin_imgs\\blsp_boot2.bin"
cfg2_bin_input = "C:\\msys64\\home\\msys\\bl602_rgb_controller\\customer_app\\custom_app\\build_out\\custom_app.bin"
meida_bin_input = ""
romfs_dir_input = ""
mfg_bin_input = ""
img_bin_input = ""
